// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4toiPa4iq8mqyQEgZEF2YT9etpsMzgk',
    appId: '1:261016421853:web:85cddf02d4a70eb83ea234',
    messagingSenderId: '261016421853',
    projectId: 'foodapp-fb3c5',
    authDomain: 'foodapp-fb3c5.firebaseapp.com',
    storageBucket: 'foodapp-fb3c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLS0FBkpqo_ErHXbILT40oxzvgYxNsCug',
    appId: '1:261016421853:android:6dad358e7c5794263ea234',
    messagingSenderId: '261016421853',
    projectId: 'foodapp-fb3c5',
    storageBucket: 'foodapp-fb3c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwuAEvrjJpQ7ZYOQhUIljyLnoc6Xlhnmc',
    appId: '1:261016421853:ios:914de4b5d93be7b53ea234',
    messagingSenderId: '261016421853',
    projectId: 'foodapp-fb3c5',
    storageBucket: 'foodapp-fb3c5.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );
}
